version: "3.8"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jooliadb
      MYSQL_USER: joolia
      MYSQL_PASSWORD: 12345
    ports:
    - "3306:3306"
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:5.0
    ports:
    - "6379:6379"
