Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
  end


  if Vagrant.has_plugin?('vagrant-certificates')
    config.certificates.enabled = true
    config.certificates.certs = Dir.glob('./*.crt')
  else
    raise 'vagrant-certificates plugin not installed!'
  end


  config.vm.provision "docker" do |d|
    d.pull_images "mysql:5.7"
    d.run "mysql",
      image: "mysql:5.7",
      args: "-p 3306:3306 -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=jooliadb"
    d.pull_images "redis:5.0"
    d.run "redis5",
      image: "redis:5.0",
      args: "-p 6379:6379"
  end

  ########################################################################
  ### Port mapping
  ########################################################################
  config.vm.network "forwarded_port", guest: 3306, host_ip: "127.0.0.1", host: 3306 #mysql
  config.vm.network "forwarded_port", guest: 6379, host_ip: "127.0.0.1", host: 6379 #redis
end
